# Site settings
author: JJ Marshall
title: JJ Baby's Blog Days
header-img: img/home-bg.png
email: johnjamesmarshalljr@gmail.com
copyright_name: JJ Marshall
description: > # this means to ignore newlines until "baseurl:"
  Programming Your Mind
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jerkzilla

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
